name: Main workflow

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        coq_version:
          - "8.19"
        ocaml_version:
          - "4.14-flambda"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: coq-community/docker-coq-action@v1
        with:
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}

          before_install: |
            startGroup "Workaround permission issue"
              sudo chown -R coq:coq . /usr/local
            endGroup

          # https://github.com/coq-community/docker-coq-action#permissions
          install: |
            startGroup "Install coq2html"
              git clone https://github.com/xavierleroy/coq2html
              cd coq2html
              make
              make install
              cd -
              rm -rf coq2html
            endGroup
            #startGroup "Install Alectryon"
            #  sudo apt-get update
            #  sudo apt-get install -y pipx python3-pip
            #  pipx install alectryon
            #endGroup

          script: |
            startGroup "Build project"
              make
              make docs
              #make alectryon
            endGroup

      # why does this take so long?
      # - name: Revert permissions
      #   # to avoid a warning at cleanup time
      #   if: ${{ always() }}
      #   run: |
      #     sudo chown -R 1001:116 . /usr/local

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          force_orphan: true
